url_scan_path = "url_scan_rt\\scan_result_"
yara_rules_path = "rules\\" 
driver_path = "chromedriver_100.exe" 
src_file = "websrc\\websrc_"
log_file = "logs\\log_"
src_ext = ".txt"
url_ext = ".json"
download_dir = "download_dir\\"
